menu:
  - name: Home
    url: index.html
  - name: Getting started
    url: getting_started.html
  - name: Examples
  - name: Documentation
  - name: Development
  - name: API progress
    url: api_progress.html
exclude:
  - test
  - utils
  - vendor
  - tools
  - node_modules
  - jsnx
  - jsnetworkx-test.js
  - scripts
